spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 210138418334-8lps4ikr6147mm361593c8am5b6eekdu.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/body_record
    username: root
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

file:
  multipart:
    max-file-size : 10MB
    max-request-size : 10MB
    location: D:\files
    enabled : true

jwt:
  time:
    access: 3600000
    refresh: 1209600000
  secret:
    access: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923
    refresh: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    sql:
      init:
        data-locations: classpath*:db/data.sql
        mode: always
        platform: mysql